### ISSUE TITLE
incorrect setup.py version

### ISSUE THREAD

**Issue by anthrotype** [jonparrott/cmarkgfm#5]
pypi says the last version is 0.3.0, uploaded on March 21
https://pypi.org/project/cmarkgfm/#history

but setup.py still has 0.2.0
https://github.com/jonparrott/cmarkgfm/blob/f263f81a922b5991a98503b4f90350daf7f97872/setup.py#L13

**Comment by jonparrott** [comment]
Hrm. I wonder if I forgot to push something. I'll re-check this when I'm back at my windows machine.

**Comment by jonparrott** [comment]
Yep I forgot to push. Silly me. It's all pushed up now.
